-- DROP DATABASE IF EXISTS top_tracks;
-- CREATE DATABASE top_tracks;
-- \c top_tracks

DROP TABLE IF EXISTS tracks;
DROP TABLE IF EXISTS artists;

CREATE TABLE artists (
  id SERIAL PRIMARY KEY,
  name VARCHAR(200) NOT NULL
);

CREATE TABLE tracks (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  image VARCHAR(200) NOT NULL,
  playcount INTEGER NOT NULL,
  length VARCHAR(50) NOT NULL,
  artist_id INTEGER NOT NULL
);

